import React from 'react'
export const items = [
  {
    id: 1,
    title: 'Terminus Liberté 5 - Tivaoune',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Tivaouane',
    ],
    price: 2000,
  },
  {
    id: 2,
    title: 'Terminus Liberté 5 - Fatick',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Sandiara',
      'Fatick',
    ],
    price: 3000,
  },
  {
    id: 3,
    title: 'Terminus Liberté 5 - Kaolack',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Sandiara',
      'Fatick',
      'Kaolack',
    ],
    price: 4000,
  },
  {
    id: 4,
    title: 'Terminus Liberté 5 - Podor & Ndioum',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Guéoul',
      'Louga',
      'Saint-Louis',
      'Ross-Béthio',
      'Richard-Toll',
      'Dagana',
      'Podor & Ndioum',
    ],
    price: 8000,
  },
  {
    id: 5,
    title: 'Terminus Liberté 5 - Saint-Louis',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Tivaouane',
      'Guéoul',
      'Louga',
      'Saint-Louis',
    ],
    price: 5000,
  },
  {
    id: 6,
    title: 'Terminus Liberté 5 - Ziguinchor',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Keur Ayip',
      'Pont Sénégambie',
      'Sénoba',
      'Bounkiling',
      'Bignona',
      'Ziguinchor',
    ],
    price: 9000,
  },
  {
    id: 7,
    title: 'Terminus Liberté 5 - Ourossogui/Matam',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Touba',
      'Dara',
      'Linguère',
      'Ranéou',
      'Ourossogui/Matam',
    ],
    price: 10000,
  },
  {
    id: 8,
    title: 'Terminus Liberté 5 - Kaffrine',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
    ],
    price: 5000,
  },
  {
    id: 9,
    title: 'Terminus Liberté 5 - Koungheul',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
    ],
    price: 6000,
  },
  {
    id: 10,
    title: 'Terminus Liberté 5 - Tambacounda',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
    ],
    price: 9000,
  },
  {
    id: 11,
    title: 'Terminus Liberté 5 - Vélingara',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
      'Vélingara',
    ],
    price: 11000,
  },
  {
    id: 12,
    title: 'Terminus Liberté 5 - Kolda',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
      'Vélingara',
      'Kolda',
    ],
    price: 14000,
  },
  {
    id: 13,
    title: 'Terminus Liberté 5 - Thiès',
    destination: ['Terminus Liberté 5', 'autoroute à péage', 'Thiès '],
    price: 2000,
  },
  {
    id: 14,
    title: 'Terminus Liberté 5 - Diourbel',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Diourbel',
    ],
    price: 3000,
  },
  {
    id: 15,
    title: 'Terminus Liberté 5 - Touba',
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Diourbel',
      'Touba',
    ],
    price: 4000,
  },
]
