export const data = [
  {
    id: 1,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Tivaouane',
    ],
    price: 2000,
    time:
      'Mondays, Tuesdays, Wednesdays, Thursdays & Saturdays at 3 p.m. & 6 p.m. Fridays at 10 a.m., 4 p.m. and 6 p.m',
    operator: 'http://demdikk.com/',
  },
  {
    id: 2,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Sandiara ',
      'Fatick',
    ],
    price: 3000,
    time: 'Every day from 7am - 3pm',
    operator: 'http://demdikk.com/',
    //payment:""
  },
  {
    id: 3,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Sandiara',
      'Fatick',
      'Kaolack',
    ],
    price: 4000,
    time: 'Every day from 7am - 3pm',
    operator: 'http://demdikk.com/',
  },
  {
    id: 4,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Guéoul',
      'Louga',
      'Saint-Louis',
      'Ross-Béthio',
      'Richard-Toll',
      'Dagana',
      'Podor & Ndioum',
    ],
    price: 8000,
    time: 'Every day 7 am & 3 pm except Wednesdays. ',
    operator: 'http://demdikk.com/',
  },
  {
    id: 5,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Tivaouane',
      'Guéoul',
      'Louga',
      'Saint-Louis',
    ],
    price: 5000,

    time: 'Every day 7 am & 3 pm ',
    operator: 'http://demdikk.com/',
  },
  {
    id: 6,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Keur Ayip',
      'Pont Sénégambie',
      'Sénoba',
      'Bounkiling',
      'Bignona',
      'Ziguinchor',
    ],
    price: 9000,
    time: 'Every day at 8 am from Dakar and 6 am from Ziguinchor',
    operator: 'http://demdikk.com/',
    notification:
      'The presentation of the valid identity document or passport is compulsory on this journey. It is compulsory for each child to have a birth certificate accompanied by his biological parents or a parental authorization if the child is accompanied by a person other than his parents. Children and minors do not travel alone.',
  },
  {
    id: 7,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Touba',
      'Dara',
      'Linguère',
      'Ranéou',
      'Ourossogui/Matam',
    ],
    price: 10000,
    time:
      'Mondays, Thursdays & Saturdays at 8 a.m. from Dakar and 6 a.m. from Ourossogui / Matam.',
    operator: 'http://demdikk.com/',
  },
  {
    id: 8,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
    ],
    price: 5000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 9,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
    ],
    price: 6000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 10,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
    ],
    price: 9000,

    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 11,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
      'Vélingara',
    ],
    price: 11000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 12,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
      'Vélingara',
      'Kolda',
    ],
    price: 14000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 13,
    destination: ['Terminus Liberté 5', 'autoroute à péage', 'Thiès'],
    price: 2000,

    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar.',
    operator: 'http://demdikk.com/',
  },
  {
    id: 14,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Diourbel',
    ],
    price: 3000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 15,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Diourbel',
      'route nationale jusqu’à Touba',
    ],
    price: 4000,
    time:
      'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar and 6 a.m. from Kolda.',
    operator: 'http://demdikk.com/',
  },
]
export const data1 = [
  {
    id: 1,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Tivaouane',
    ],
    price: 2000,
    time:
      'Mondays, Tuesdays, Wednesdays, Thursdays & Saturdays at 3 p.m. & 6 p.m. Fridays at 10 a.m., 4 p.m. and 6 p.m',
    operator: 'http://demdikk.com/',
  },
  {
    id: 2,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Sandiara ',
      'Fatick',
    ],
    price: 3000,
    time: 'Every day from 7am - 3pm',
    operator: 'http://demdikk.com/',
    //payment:""
  },
  {
    id: 3,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Sandiara',
      'Fatick',
      'Kaolack',
    ],
    price: 4000,
    time: 'Every day from 7am - 3pm',
    operator: 'http://demdikk.com/',
  },
  {
    id: 4,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Guéoul',
      'Louga',
      'Saint-Louis',
      'Ross-Béthio',
      'Richard-Toll',
      'Dagana',
      'Podor & Ndioum',
    ],
    price: 8000,
    time: 'Every day 7 am & 3 pm except Wednesdays. ',
    operator: 'http://demdikk.com/',
  },
  {
    id: 5,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Thiès',
      'Tivaouane',
      'Guéoul',
      'Louga',
      'Saint-Louis',
    ],
    price: 5000,

    time: 'Every day 7 am & 3 pm ',
    operator: 'http://demdikk.com/',
  },
  {
    id: 6,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Keur Ayip',
      'Pont Sénégambie',
      'Sénoba',
      'Bounkiling',
      'Bignona',
      'Ziguinchor',
    ],
    price: 9000,
    time: 'Every day at 8 am from Dakar and 6 am from Ziguinchor',
    operator: 'http://demdikk.com/',
    notification:
      'The presentation of the valid identity document or passport is compulsory on this journey. It is compulsory for each child to have a birth certificate accompanied by his biological parents or a parental authorization if the child is accompanied by a person other than his parents. Children and minors do not travel alone.',
  },
  {
    id: 7,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Touba',
      'Dara',
      'Linguère',
      'Ranéou',
      'Ourossogui/Matam',
    ],
    price: 10000,
    time:
      'Mondays, Thursdays & Saturdays at 8 a.m. from Dakar and 6 a.m. from Ourossogui / Matam.',
    operator: 'http://demdikk.com/',
  },
  {
    id: 8,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
    ],
    price: 5000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 9,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
    ],
    price: 6000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 10,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
    ],
    price: 9000,

    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 11,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
      'Vélingara',
    ],
    price: 11000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 12,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Sindia',
      'Mbour',
      'Fatick',
      'Kaolack',
      'Kaffrine',
      'Koungheul',
      'Tambacounda',
      'Vélingara',
      'Kolda',
    ],
    price: 14000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 13,
    destination: ['Terminus Liberté 5', 'autoroute à péage', 'Thiès'],
    price: 2000,

    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar.',
    operator: 'http://demdikk.com/',
  },
  {
    id: 14,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Diourbel',
    ],
    price: 3000,
    time: 'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar',
    operator: 'http://demdikk.com/',
  },
  {
    id: 15,
    destination: [
      'Terminus Liberté 5',
      'autoroute à péage',
      'Ila Touba',
      'Diourbel',
      'route nationale jusqu’à Touba',
    ],
    price: 4000,
    time:
      'Tuesdays, Fridays & Sundays at 8 a.m. from Dakar and 6 a.m. from Kolda.',
    operator: 'http://demdikk.com/',
  },
]
